"""The table `src/float/table_exp.rs` reads: 2^(k/128) for k in 0..128, as a double and a correction.

The table's definition and the six entries quoted below are from musl's src/math/exp_data.c,
Copyright (c) 2018, Arm Limited. SPDX-License-Identifier: MIT.

The algorithm is Arm's table-driven exp (optimized-routines, 2018, MIT), the one glibc and musl
ship. Its data file defines the table as

    2^(k/N) ~= H[k] * (1 + T[k])  for int k in [0, N)
    tab[2*k]   = asuint64(T[k])
    tab[2*k+1] = asuint64(H[k]) - (k << 52) / N

with N = 128: H[k] is 2^(k/N) rounded to the nearest double, and T[k] the relative error of that
rounding, itself rounded to the nearest double. This script computes both at 200 bits with mpmath,
so the table is derived rather than copied, and checks the result against the entries of musl's
src/math/exp_data.c quoted below.

Usage: uv run --no-project --with mpmath python scripts/float_exp_table.py [--check]

With --check, prints nothing and exits 1 unless src/float/table_exp.rs holds exactly this table.
"""

import re
import struct
import sys
from pathlib import Path

from mpmath import mp, mpf, power

mp.prec = 200
N = 128


def bits(value: float) -> int:
    return struct.unpack("<Q", struct.pack("<d", value))[0]


def nearest_double(value) -> float:
    # mpmath rounds to nearest, ties to even, when converting at the double's precision.
    with mp.workprec(53):
        return float(+value)


rows = []
for k in range(N):
    exact = power(mpf(2), mpf(k) / N)
    high = nearest_double(exact)
    tail = nearest_double((exact - mpf(high)) / mpf(high))
    rows.append((bits(tail), (bits(high) - (k << 52) // N) % (1 << 64)))

# Entries as written in musl's src/math/exp_data.c (first four and last two pairs).
quoted = {
    0: (0x0, 0x3FF0000000000000),
    1: (0x3C9B3B4F1A88BF6E, 0x3FEFF63DA9FB3335),
    2: (0xBC7160139CD8DC5D, 0x3FEFEC9A3E778061),
    3: (0xBC905E7A108766D1, 0x3FEFE315E86E7F85),
    126: (0x3C77893B4D91CD9D, 0x3FEFE7C1819E90D8),
    127: (0x3C5305C14160CC89, 0x3FEFF3C22B8F71F1),
}
for k, pair in quoted.items():
    assert rows[k] == pair, f"k={k}: computed {rows[k][0]:#x}, {rows[k][1]:#x}"

lines = ["// Generated by scripts/float_exp_table.py; do not edit by hand.", "#[rustfmt::skip]",
         "const TABLE: [u64; 2 * N as usize] = ["]
lines += [f"    {tail:#018x}, {high:#018x}," for tail, high in rows]
lines.append("];")

if "--check" in sys.argv:
    source = (Path(__file__).resolve().parent.parent / "src/float/table_exp.rs").read_text()
    block = re.search(r"const TABLE: \[u64; 2 \* N as usize\] = \[(.*?)\];", source, re.S)
    found = [int(word, 16) for word in re.findall(r"0x[0-9a-f]+", block.group(1))] if block else []
    expected = [word for pair in rows for word in pair]
    if found != expected:
        sys.exit("src/float/table_exp.rs's TABLE is not this script's output")
else:
    print("\n".join(lines))
